#!/bin/bash

this script to do basic git backups without typing commands again and again
#save the script in ~/bin for it to be executable

echo -e "\n\033[1mCommitting git backup\033[0m\n"

cd ${PWD}
git add . 
read -p "Enter your commit message:" commit_message

echo

echo "Your commit message is: $commit_message"

read -p "Should we proceed(Y/n): " yn
case $yn in 
	"" | [Yy]*) 
		echo "Commiting......."
		git commit -m "$commit_message | backup->`date`"
		git push origin
		;;
	[Nn]*) 
		echo "Abort"
		exit 1
		;;	
	*)
		echo "MF respond correctly!"
		exit 1
		;;
esac


